title: 18th International Particle Accelerator Conference
description: IPAC'27, hosted by Facility Rare Isotope Beams at Michigan State Univeristy
remote_theme: IPAC2027/hacker@v0.2.0
plugins:
- jekyll-remote-them

view_on_github: false
