title: 18th International Particle Accelerator Conference
description: IPAC'27, hosted by Facility Rare Isotope Beams at Michigan State Univeristy
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-them

github:
  is_project_page: false
