title: 18th International Particle Accelerator Conference
description: IPAC'27, hosted by Facility Rare Isotope Beams at Michigan State Univeristy
  # remote_theme: IPAC2027/hacker@d6dde7f
remote_theme: pages-themes/hacker@e3c8d1ad288894be216002a5bc29fc611aeab9ac
plugins:
- jekyll-remote-them

view_on_github: false
