// MC3: Advanced Acceleration Techniques and Novel Particle Sources — invited speakers for IPAC'27
import type { Speaker } from './types';

export const mc3Speakers: Speaker[] = [
  {
    id: "samuel-barber",
    name: "Samuel Barber",
    affiliation: `Lawrence Berkeley National Laboratory`,
    type: "invited",
    title: ``,
    classification: "MC3",
    session: {},
    schedule: { date: "2027-05-24", startTime: "14:00", endTime: "14:30", room: "Grand Riverview Ballroom A" },
  },
  {
    id: "mario-galletti",
    name: "Mario Galletti",
    affiliation: `Italian National Institute for Nuclear Physics`,
    photo: "/images/speakers/mario-galletti.jpeg",
    photoAdjustment: { position: "center 15%" },
    bio: `Mario Galletti is a Senior Researcher at the Frascati National Laboratories (LNF) of the Italian National Institute for Nuclear Physics (INFN), where he conducts research on advanced accelerator concepts, high-power laser systems, and plasma-based particle acceleration. He received his M.Sc. in Physics from the University of Pisa and his Ph.D. in Physics Engineering from Instituto Superior Técnico, University of Lisbon, in 2020.
His research focuses on laser- and beam-driven plasma wakefield acceleration, free-electron lasers, beam diagnostics, and the development of compact accelerator technologies for scientific applications. He has played a leading role in several international collaborations, including EuPRAXIA, contributing to pioneering demonstrations of plasma-driven free-electron lasers and innovative plasma accelerator technologies. He is the lead or corresponding author of numerous high-impact publications in journals such as Nature, Nature Photonics, Physical Review Letters, and Physical Review.
Dr. Galletti has received several prestigious awards, including the 2024 SILS Young Scientist Award and the European Physical Society Plasma Physics Division PhD Research Award. He is actively involved in teaching, mentoring young researchers, coordinating international research activities, and serving as reviewer and editor for leading scientific journals.`,
    type: "invited",
    title: `Beam-driven wakefield acceleration in laser-plasma filament`,
    abstract: `The talk will report on the experimental demonstration of plasma-based electron acceleration using laser-generated plasma filament as acceleration stage. The experiments are performed at SPARC_LAB (INFN - Frascati). The work builds on a complete experimental and theoretical characterisation of plasma filaments generated by low-energy (10 mJ), self-guided femtosecond laser pulses in low-pressure nitrogen [1]. This approach allows for proposing plasma filaments as tunable, high repetition-rate, low-energy dissipation plasma acceleration stages, with potential scalability of the interaction length to the meter scale. These features make filament-based stages particularly attractive for future light sources facilities based on plasma accelerators, as EuPRAXIA and EuPRAXIA-related systems. This work could be of broad interest because it introduces, for the first time, a beam-driven plasma acceleration stage based on the nonlinear self-guided propagation of an ultrashort laser pulse, rather than externally confined or preformed plasma structures. Beyond particle acceleration, this concept naturally connects to several topical areas, including nonlinear light–matter interaction, laser filamentation physics, compact accelerator technologies, and advanced plasma photonics.`,
    classification: "MC3",
    session: {},
    schedule: { date: "2027-05-25", startTime: "11:00", endTime: "11:30", room: "Grand Riverview Ballroom B" },
  },
  {
    id: "renkai-li",
    name: "Renkai Li",
    affiliation: `Tsinghua University in Beijing`,
    type: "invited",
    title: ``,
    classification: "MC3",
    session: {},
    schedule: { date: "2027-05-24", startTime: "14:30", endTime: "15:00", room: "Grand Riverview Ballroom A" },
  },
];
