// MC3: Advanced Acceleration Techniques and Novel Particle Sources — invited speakers for IPAC'27
import type { Speaker } from './types';

export const mc3Speakers: Speaker[] = [
  {
    id: "samuel-barber",
    name: "Samuel Barber",
    photo: "/images/speakers/samuel-barber.png",
    photoAdjustment: { position: "center 10%", zoom: 1.1 },
    bio: `Samuel (Sam) Barber is a research scientist in the Accelerator Technology and Applied Physics (ATAP) Division at Lawrence Berkeley National Laboratory (LBNL), where he works at the Berkeley Lab Laser Accelerator (BELLA) Center. His research focuses on laser-plasma acceleration (LPA) and the development of next-generation, compact light sources driven by high-brightness electron beams. His work explores the application of LPA technology to free-electron lasers (FELs), with the goal of making advanced X-ray and other photon sources more compact and accessible to the scientific community. Barber has made key contributions to improving accelerator stability, electron-beam quality, and the integration of plasma accelerators with undulator-based radiation sources. His research helped advance the demonstration of coherent gain in an LPA-driven free-electron laser, establishing an important milestone toward compact FEL technology. In recognition of his contributions, he received Berkeley Lab’s 2023 Director’s Award for Exceptional Early Scientific Career Achievement. Barber earned his B.S. in Astrophysics, M.S. in Physics, and Ph.D. in Physics from the University of California, Los Angeles.`,
    affiliation: `Lawrence Berkeley National Laboratory`,
    type: "invited",
    title: `Compact free-electron lasers driven by plasma-based accelerators`,
    abstract: `Compact free-electron lasers (FELs) that are driven by plasma-based accelerators have been a dream for years. Over the past few years several milestone experiments have demonstrated their basic feasibility, and the BELLA lab at LBNL has recently demonstrated FEL gains exceeding 1000 at optical wavelengths. We report on these findings, and discuss our next steps to towards demonstrating FEL gain to full saturation. We then examine the present status of plasma-based sources regarding reliability and stability, and discuss a possible route towards improving these characteristics to the level required for an operational light source.`,
    classification: "MC3",
    session: {},
    schedule: { date: "2027-05-24", startTime: "14:00", endTime: "14:30", room: "Grand Riverview Ballroom A" },
  },
  {
    id: "mario-galletti",
    name: "Mario Galletti",
    affiliation: `Italian National Institute for Nuclear Physics`,
    photo: "/images/speakers/mario-galletti.jpeg",
    photoAdjustment: { position: "center 15%" },
    bio: `Mario Galletti is a Senior Researcher at the Frascati National Laboratories (LNF) of the Italian National Institute for Nuclear Physics (INFN), where he conducts research on advanced accelerator concepts, high-power laser systems, and plasma-based particle acceleration. He received his M.Sc. in Physics from the University of Pisa and his Ph.D. in Physics Engineering from Instituto Superior Técnico, University of Lisbon, in 2020.
His research focuses on laser- and beam-driven plasma wakefield acceleration, free-electron lasers, beam diagnostics, and the development of compact accelerator technologies for scientific applications. He has played a leading role in several international collaborations, including EuPRAXIA, contributing to pioneering demonstrations of plasma-driven free-electron lasers and innovative plasma accelerator technologies. He is the lead or corresponding author of numerous high-impact publications in journals such as Nature, Nature Photonics, Physical Review Letters, and Physical Review.
Dr. Galletti has received several prestigious awards, including the 2024 SILS Young Scientist Award and the European Physical Society Plasma Physics Division PhD Research Award. He is actively involved in teaching, mentoring young researchers, coordinating international research activities, and serving as reviewer and editor for leading scientific journals.`,
    type: "invited",
    title: `Beam-driven wakefield acceleration in laser-plasma filament`,
    abstract: `The talk will report on the experimental demonstration of plasma-based electron acceleration using laser-generated plasma filament as acceleration stage. The experiments are performed at SPARC_LAB (INFN - Frascati). The work builds on a complete experimental and theoretical characterisation of plasma filaments generated by low-energy (10 mJ), self-guided femtosecond laser pulses in low-pressure nitrogen [1]. This approach allows for proposing plasma filaments as tunable, high repetition-rate, low-energy dissipation plasma acceleration stages, with potential scalability of the interaction length to the meter scale. These features make filament-based stages particularly attractive for future light sources facilities based on plasma accelerators, as EuPRAXIA and EuPRAXIA-related systems. This work could be of broad interest because it introduces, for the first time, a beam-driven plasma acceleration stage based on the nonlinear self-guided propagation of an ultrashort laser pulse, rather than externally confined or preformed plasma structures. Beyond particle acceleration, this concept naturally connects to several topical areas, including nonlinear light–matter interaction, laser filamentation physics, compact accelerator technologies, and advanced plasma photonics.`,
    classification: "MC3",
    session: {},
    schedule: { date: "2027-05-25", startTime: "11:00", endTime: "11:30", room: "Grand Riverview Ballroom B" },
  },
  {
    id: "renkai-li",
    name: "Renkai Li",
    affiliation: `Tsinghua University in Beijing`,
    photo: "/images/speakers/renkai-li.jpg",
    bio: `Prof. Renkai Li received his bachelor’s and PhD degrees from Tsinghua University in 2005 and 2010, respectively. He subsequently joined UCLA as a postdoctoral researcher and later as an Assistant Researcher, where he worked until May 2014 on the physics and technologies of high-brightness electron sources. From July 2014 to April 2019, he was a Staff Scientist at SLAC National Accelerator Laboratory, where he played a major role in developing and improving a MeV ultrafast electron diffraction (UED) facility for scientific experiments. He also played a key role in the recommissioning and testing of a VHF SRF electron gun for future CW XFELs and high-repetition-rate UED and ultrafast electron microscopy. In May 2019, he joined Tsinghua University as a Full Professor. His research focuses on the physics and technology of high-brightness electron sources and beams, as well as their applications in ultrafast science.`,
    type: "invited",
    title: `Toward brighter electron sources - characterization of alkali antimonide photocathode in a high-gradient RF gun`,
    abstract: `High-brightness electron sources are essential for enabling and enhancing free-electron lasers, ultrafast electron diffraction and imaging, inverse Compton scattering sources, and other emerging applications. Combining photocathodes offering high quantum efficiency (QE), low mean transverse energy (MTE), and visible-light operation with the highest achievable accelerating field represents one of the most direct and effective routes to improving beam brightness. However, systematic studies and reliable operation of such high-performance photocathodes at very high accelerating gradients remain challenging, primarily due to stringent vacuum requirements. To address these limitations, we have developed an ultrahigh-vacuum, high-gradient S-band RF gun that substantially extends the operational lifetime of alkali antimonide photocathodes. In this work, we report measurements of the QE, MTE, and their dependence on excitation wavelength, paving the way for a new operational regime for high-brightness electron sources.`,
    classification: "MC3",
    session: {},
    schedule: { date: "2027-05-24", startTime: "14:30", endTime: "15:00", room: "Grand Riverview Ballroom A" },
  },
];
